# Generated by Django 5.0.1 on 2024-03-22 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='production_area',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.productionarea'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productionarea',
            name='prod_area_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
