# Generated by Django 3.2.18 on 2024-11-06 06:25

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='unique_id',
            field=models.CharField(default=main.models.generate_unique_id, max_length=5, unique=True),
        ),
    ]
