# Generated by Django 5.0.1 on 2024-03-05 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='staff_approved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='supervisor_approved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_approved', to=settings.AUTH_USER_MODEL),
        ),
    ]
