# Generated by Django 5.0.1 on 2024-03-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historytrading',
            name='purpose_detail',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
