# Generated by Django 3.2.18 on 2024-11-15 02:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_component_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('cost_center_number', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='equipment_type',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='component',
            name='last_inventory_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='component',
            name='next_inventory_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='component',
            name='unique_id',
            field=models.CharField(default=main.models.generate_unique_id, editable=False, max_length=5, unique=True),
        ),
        migrations.CreateModel(
            name='InventoryReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Abnormal', 'Abnormal'), ('Normal', 'Normal')], default='Abnormal', max_length=255)),
                ('missing_list', models.TextField(blank=True, null=True)),
                ('inventory_date', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.component')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.costcenter'),
        ),
    ]
