# Generated by Django 5.0.1 on 2024-03-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_historytrading_purpose_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='historytrading',
            name='po_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='historytrading',
            name='request_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
