# Generated by Django 5.0.1 on 2024-03-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_component_production_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historytrading',
            name='member',
        ),
        migrations.AddField(
            model_name='historytrading',
            name='request_id',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historytrading',
            name='username',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
