# Generated by Django 5.0.1 on 2024-03-06 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_request_requester_alter_request_staff_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='machine_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.machinetype'),
            preserve_default=False,
        ),
    ]
