# Generated by Django 4.1.4 on 2024-03-13 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_member_production_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.productionarea')),
                ('staff_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_route', to=settings.AUTH_USER_MODEL)),
                ('supervisor_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_route', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
