# Generated by Django 5.0.1 on 2024-02-21 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_historytrading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historytrading',
            old_name='Member',
            new_name='member',
        ),
    ]
