# Generated by Django 5.0.1 on 2024-03-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_requestcomponentrelation_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='component',
            new_name='components',
        ),
    ]
