# Generated by Django 5.0.1 on 2024-03-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_historytrading_member_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historytrading',
            old_name='username',
            new_name='requester',
        ),
        migrations.AddField(
            model_name='historytrading',
            name='staff_approved',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historytrading',
            name='supervisor_approved',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historytrading',
            name='trader',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
