# Generated by Django 4.1.4 on 2024-03-13 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_approvedroute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedroute',
            name='production_area',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.productionarea'),
        ),
    ]
