# Generated by Django 5.0.1 on 2024-03-06 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_machinetype_component_machine_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machinetype',
            old_name='machine_name',
            new_name='name',
        ),
    ]
