# Generated by Django 5.0.1 on 2024-03-25 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_historytrading_po_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='po',
            name='production_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.productionarea'),
        ),
    ]
