# Generated by Django 5.0.1 on 2024-03-12 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_component_request_components'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestcomponentrelation',
            old_name='component',
            new_name='component_r',
        ),
    ]
