# Generated by Django 5.0.1 on 2024-11-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_component_equipment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreport',
            name='missing_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
