# Generated by Django 3.2.18 on 2024-12-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20241219_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='missing_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
