# Generated by Django 5.0.1 on 2024-03-25 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_po_production_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historytrading',
            name='po_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.po'),
        ),
    ]
