# Generated by Django 4.1.4 on 2024-03-14 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_approvedroute_production_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
