# Generated by Django 5.0.1 on 2024-03-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_username_historytrading_requester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historytrading',
            name='requester',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historytrading',
            name='staff_approved',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historytrading',
            name='supervisor_approved',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historytrading',
            name='trader',
            field=models.CharField(max_length=100),
        ),
    ]
