# Generated by Django 5.0.1 on 2024-03-07 07:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_machine_name_machinetype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialnumber',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
