# Generated by Django 4.1.4 on 2024-03-14 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_request_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedroute',
            name='staff_route_second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_route_second', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvedroute',
            name='supervisor_route_second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_route_second', to=settings.AUTH_USER_MODEL),
        ),
    ]
