# Generated by Django 5.0.1 on 2024-03-12 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_component_r_requestcomponentrelation_component'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestcomponentrelation',
            old_name='quantity',
            new_name='qty',
        ),
        migrations.AlterField(
            model_name='requestcomponentrelation',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component', to='main.component'),
        ),
    ]
