# Generated by Django 5.0.1 on 2024-04-02 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_historytrading_po_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='production_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.productionarea'),
        ),
        migrations.AddField(
            model_name='machinetype',
            name='production_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.productionarea'),
        ),
    ]
