# Generated by Django 3.2.18 on 2024-12-25 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_component_missing_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='last_inventory_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
