# Generated by Django 5.0.1 on 2024-12-19 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_costcenter_member_cost_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryreport',
            name='component',
        ),
        migrations.AddField(
            model_name='inventoryreport',
            name='location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.location'),
            preserve_default=False,
        ),
    ]
