# Generated by Django 3.2.18 on 2024-12-27 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_location_last_inventory_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreport',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
