# Generated by Django 5.0.1 on 2024-12-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_inventoryreport_component_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='missing_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
