# Generated by Django 5.0.1 on 2024-04-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_location_production_area_machinetype_production_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='historytrading',
            name='purpose_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historytrading',
            name='scrap_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='PURPOSE_TYPE',
            field=models.TextField(choices=[('General', 'General'), ('New Project', 'New Project'), ('Exchange', 'Exchange')], default='General', max_length=255),
        ),
    ]
