# Generated by Django 4.1.4 on 2024-03-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_approvedroute_staff_route_second_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[(1, 'Requested'), (2, 'Staff'), (3, 'Manager'), (4, 'Preparing'), (5, 'Success')], default=1, max_length=255),
        ),
    ]
