# Generated by Django 5.0.1 on 2024-04-09 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_historytrading_purpose_type_historytrading_scrap_qty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='PURPOSE_TYPE',
            new_name='purpose_type',
        ),
    ]
