# Generated by Django 5.0.1 on 2024-12-25 09:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_component_missing_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='last_inventory_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
