# Generated by Django 5.0.1 on 2025-01-13 02:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_member_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcenter',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('production_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productionarea')),
            ],
        ),
        migrations.AddField(
            model_name='costcenter',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.line'),
        ),
        migrations.AddField(
            model_name='historytrading',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.line'),
        ),
        migrations.AddField(
            model_name='request',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.line'),
        ),
        migrations.CreateModel(
            name='LineSafetyStockRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('safety_number', models.PositiveIntegerField(default=1)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.component')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.line')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='safety_stock',
            field=models.ManyToManyField(through='main.LineSafetyStockRelation', to='main.line'),
        ),
    ]
