# Generated by Django 3.2.18 on 2025-01-15 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_member_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_name', models.CharField(max_length=10, unique=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('production_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productionarea')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='added_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_c_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='component',
            name='modify_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modify_c_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='LineSafetyStockRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('safety_number', models.PositiveIntegerField(default=1)),
                ('modify_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('added_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_ls_member', to=settings.AUTH_USER_MODEL)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.component')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.line')),
                ('modify_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modify_ls_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='safety_stock',
            field=models.ManyToManyField(through='main.LineSafetyStockRelation', to='main.Line'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.line'),
        ),
        migrations.AddField(
            model_name='historytrading',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.line'),
        ),
        migrations.AddField(
            model_name='request',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.line'),
        ),
    ]
