# Generated by Django 4.1.4 on 2024-03-14 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='prepare_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prepare_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
