# Generated by Django 5.0.1 on 2024-04-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_purpose_type_request_purpose_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_center',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='requester_name',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
