# Generated by Django 5.0.1 on 2024-04-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_member_is_center_request_requester_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='requester_name',
            new_name='requester_name_center',
        ),
        migrations.AddField(
            model_name='request',
            name='requester_name_emp',
            field=models.TextField(blank=True, max_length=8, null=True),
        ),
    ]
