# Generated by Django 5.0.1 on 2025-01-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_inventoryreport_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='department',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
