# Generated by Django 4.1.4 on 2024-03-15 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_request_prepare_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='purpose_detail',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
    ]
