# Generated by Django 5.0.1 on 2025-01-13 04:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_costcenter_id_line_costcenter_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='added_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_c_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='component',
            name='modify_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modify_c_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='linesafetystockrelation',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linesafetystockrelation',
            name='added_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_ls_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='linesafetystockrelation',
            name='modify_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='linesafetystockrelation',
            name='modify_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modify_ls_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='line',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
