# Generated by Django 3.2.18 on 2025-01-16 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20250115_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historytrading',
            name='line',
        ),
        migrations.RemoveField(
            model_name='request',
            name='line',
        ),
        migrations.AddField(
            model_name='historytrading',
            name='lines',
            field=models.ManyToManyField(related_name='lines_history', to='main.Line'),
        ),
        migrations.AddField(
            model_name='request',
            name='lines',
            field=models.ManyToManyField(related_name='lines_request', to='main.Line'),
        ),
    ]
