# Generated by Django 5.0.1 on 2025-01-14 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_component_added_member_component_modify_member_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line',
            old_name='name',
            new_name='line_name',
        ),
    ]
