# Generated by Django 5.0.1 on 2024-03-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_request_purpose_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='purpose_detail',
        ),
        migrations.AddField(
            model_name='component',
            name='unique_id',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
