# Generated by Django 5.0.1 on 2025-01-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_name_line_line_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historytrading',
            name='line',
        ),
        migrations.RemoveField(
            model_name='request',
            name='line',
        ),
        migrations.AddField(
            model_name='historytrading',
            name='lines',
            field=models.ManyToManyField(related_name='lines_history', to='main.line'),
        ),
        migrations.AddField(
            model_name='request',
            name='lines',
            field=models.ManyToManyField(related_name='lines_request', to='main.line'),
        ),
    ]
