# Generated by Django 5.0.1 on 2024-03-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_component_purpose_detail_component_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='serial_numbers',
            field=models.TextField(blank=True),
        ),
    ]
