# Generated by Django 5.0.1 on 2024-04-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_requester_name_emp_request_requester_emp_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='requester_emp_center',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='requester_name_center',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
