# Generated by Django 5.0.1 on 2025-03-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_carboncopyroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='mro_pn',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
