# Generated by Django 5.0.1 on 2025-03-24 04:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_component_mro_pn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='safety_stock',
        ),
        migrations.RemoveField(
            model_name='component',
            name='equipment_type',
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('production_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.productionarea')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentTypeRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('safety_number', models.PositiveIntegerField(default=1)),
                ('modify_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('added_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_ls_member', to=settings.AUTH_USER_MODEL)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.component')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.equipmenttype')),
                ('modify_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modify_ls_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='LineSafetyStockRelation',
        ),
        migrations.AddField(
            model_name='component',
            name='equipment_type',
            field=models.ManyToManyField(through='main.EquipmentTypeRelation', to='main.equipmenttype'),
        ),
    ]
