# Generated by Django 5.0.1 on 2024-03-21 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_request_serial_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='serial_numbers',
        ),
        migrations.AddField(
            model_name='serialnumber',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.request'),
        ),
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
