# Generated by Django 5.0.1 on 2025-03-25 08:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_component_safety_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='safety_type',
            field=models.CharField(choices=[('General', 'General'), ('DSM', 'DSM'), ('Non-DSM', 'Non-DSM')], default='General', max_length=255),
        ),
        migrations.RemoveField(
            model_name='component',
            name='machine_type',
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='equipmenttyperelation',
            name='added_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_els_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipmenttyperelation',
            name='modify_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modify_els_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MachineTypeRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('safety_number', models.PositiveIntegerField(default=1)),
                ('modify_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('added_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_mls_member', to=settings.AUTH_USER_MODEL)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.component')),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.machinetype')),
                ('modify_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modify_mls_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='machine_type',
            field=models.ManyToManyField(through='main.MachineTypeRelation', to='main.machinetype'),
        ),
    ]
