# Generated by Django 5.0.1 on 2024-04-09 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_request_scrap_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='scrap_status',
        ),
    ]
