# Generated by Django 5.0.1 on 2024-03-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_serialnumber_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='complete_date',
            field=models.DateTimeField(),
        ),
    ]
