# Generated by Django 5.1.5 on 2025-04-10 01:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_equipmenttype_quantity_machinetype_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowerRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permanent_borrowing', models.BooleanField(default=False)),
                ('borrowed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tooling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_amount', models.IntegerField()),
                ('quantity_available', models.IntegerField()),
                ('borrower', models.ManyToManyField(through='main.BorrowerRelation', to=settings.AUTH_USER_MODEL)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.component')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.location')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryToolTrading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('Borrow', 'Borrow'), ('Return', 'Return')], default='Borrow', max_length=255)),
                ('borrower', models.CharField(max_length=100)),
                ('trader', models.CharField(max_length=100)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('tooling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tooling')),
            ],
        ),
        migrations.AddField(
            model_name='borrowerrelation',
            name='tooling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tooling'),
        ),
    ]
