# Generated by Django 5.0.1 on 2025-03-25 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_component_safety_type_remove_component_machine_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='safety_type',
        ),
    ]
