# Generated by Django 5.0.1 on 2024-04-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_request_scrap_list_request_scrap_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='scrap_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
