# Generated by Django 5.0.1 on 2024-03-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_request_complete_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='complete_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
