# Generated by Django 5.1.5 on 2025-04-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_borrowerrelation_tooling_historytooltrading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='for_tooling',
            field=models.BooleanField(default=False),
        ),
    ]
