# Generated by Django 5.0.1 on 2025-03-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_component_safety_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinetype',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
