# Generated by Django 5.0.1 on 2025-03-26 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_machinetype_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productionarea',
            name='schema',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
