# Generated by Django 5.1.5 on 2025-04-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_location_for_tooling'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_role',
            field=models.CharField(choices=[('NONE', 'NONE'), ('AME', 'AME'), ('TE', 'TE'), ('PRODUCTION', 'PRODUCTION'), ('IE', 'IE')], default='NONE', max_length=255),
        ),
    ]
