# Generated by Django 5.0.1 on 2024-04-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_request_scrap_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='historytrading',
            name='scrap_serial_numbers',
            field=models.TextField(default=''),
        ),
    ]
