# Generated by Django 5.0.1 on 2024-04-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_historytrading_scrap_serial_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='self_pick',
            field=models.BooleanField(default=False),
        ),
    ]
