# Generated by Django 5.1.5 on 2025-05-26 11:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_member_member_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedroute',
            name='approve_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approve_route', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historytrading',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='member',
            name='is_local',
            field=models.BooleanField(default=False),
        ),
    ]
