# Generated by Django 5.0.1 on 2025-04-01 07:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_productionarea_schema_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowerRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tooling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_amount', models.IntegerField()),
                ('quantity_available', models.IntegerField()),
                ('borrower', models.ManyToManyField(through='main.BorrowerRelation', to=settings.AUTH_USER_MODEL)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.component')),
            ],
        ),
        migrations.AddField(
            model_name='borrowerrelation',
            name='tooling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tooling'),
        ),
    ]
