# Generated by Django 5.1.5 on 2025-05-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='pickup_status',
            field=models.BooleanField(default=False),
        ),
    ]
