# Generated by Django 5.0.1 on 2025-04-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_borrowerrelation_tooling_borrowerrelation_tooling'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowerrelation',
            old_name='borrow_date',
            new_name='borrowed_date',
        ),
        migrations.AddField(
            model_name='borrowerrelation',
            name='borrowed_permanent',
            field=models.BooleanField(default=False),
        ),
    ]
