# Generated by Django 5.0.1 on 2024-04-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_request_self_pick'),
    ]

    operations = [
        migrations.AddField(
            model_name='historytrading',
            name='left_qty',
            field=models.IntegerField(default=0),
        ),
    ]
