# Generated by Django 5.0.1 on 2025-04-04 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rename_borrow_date_borrowerrelation_borrowed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tooling',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.location'),
        ),
    ]
