# Generated by Django 5.1.5 on 2025-05-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_request_pickup_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_administrator',
            field=models.BooleanField(default=False),
        ),
    ]
