# Generated by Django 5.0.1 on 2024-04-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_historytrading_left_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historytrading',
            name='scrap_serial_numbers',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='historytrading',
            name='serial_numbers',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
