# Generated by Django 5.0.1 on 2025-04-09 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_tooling_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryToolTrading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Borrow', 'Borrow'), ('Return', 'Return')], default='Borrow', max_length=255)),
                ('borrower', models.CharField(max_length=100)),
                ('trader', models.CharField(max_length=100)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('tooling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tooling')),
            ],
        ),
    ]
