# Generated by Django 5.1.5 on 2025-06-12 02:33

import django.db.models.deletion
import django.utils.timezone
import main.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_member_image_alter_member_member_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='line_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='tel',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_role',
            field=models.CharField(choices=[('NONE', 'NONE'), ('User', 'User'), ('Fixture Staff', 'Fixture Staff'), ('Spare Part Staff', 'Spare Part Staff'), ('Modify Part Staff', 'Modify Part Staff'), ('Management Staff', 'Management Staff'), ('-', '-')], default='NONE', max_length=255),
        ),
        migrations.CreateModel(
            name='ShiftDuty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('period_end', models.DateTimeField(default=main.models.one_week_later)),
                ('production_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.productionarea')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftDutyRelative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shift', models.CharField(choices=[('DAY', 'DAY'), ('NIGHT', 'NIGHT')], default='DAY', max_length=255)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shift_duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shiftduty')),
            ],
        ),
        migrations.AddField(
            model_name='shiftduty',
            name='members',
            field=models.ManyToManyField(through='main.ShiftDutyRelative', to=settings.AUTH_USER_MODEL),
        ),
    ]
