# Generated by Django 5.0.1 on 2025-04-09 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_historytooltrading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historytooltrading',
            old_name='status',
            new_name='topic',
        ),
    ]
