# Generated by Django 5.0.1 on 2025-04-09 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_rename_status_historytooltrading_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowerrelation',
            old_name='borrowed_permanent',
            new_name='permanent_borrowing',
        ),
    ]
