# Generated by Django 5.1.5 on 2025-06-13 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_member_line_id_member_tel_alter_member_member_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftduty',
            name='members',
        ),
        migrations.AddField(
            model_name='shiftduty',
            name='member',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shiftduty',
            name='shift',
            field=models.CharField(choices=[('DAY', 'DAY'), ('NIGHT', 'NIGHT')], default='DAY', max_length=255),
        ),
        migrations.DeleteModel(
            name='ShiftDutyRelative',
        ),
    ]
