# Generated by Django 5.0.1 on 2024-04-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_historytrading_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historytrading',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
