# Generated by Django 5.1.5 on 2025-07-02 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_shiftduty_members_shiftduty_member_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmenttyperelation',
            old_name='safety_number',
            new_name='m_quantity',
        ),
        migrations.RenameField(
            model_name='machinetyperelation',
            old_name='safety_number',
            new_name='m_quantity',
        ),
        migrations.RemoveField(
            model_name='equipmenttype',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='machinetype',
            name='quantity',
        ),
        migrations.AddField(
            model_name='equipmenttyperelation',
            name='factor',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='equipmenttyperelation',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.line'),
        ),
        migrations.AddField(
            model_name='machinetyperelation',
            name='factor',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='machinetyperelation',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.line'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AddConstraint(
            model_name='equipmenttype',
            constraint=models.UniqueConstraint(fields=('name', 'production_area'), name='unique_equipment_type_per_area'),
        ),
        migrations.AddConstraint(
            model_name='equipmenttyperelation',
            constraint=models.UniqueConstraint(fields=('equipment_type', 'line'), name='unique_equipment_type_per_line'),
        ),
        migrations.AddConstraint(
            model_name='machinetype',
            constraint=models.UniqueConstraint(fields=('name', 'production_area'), name='unique_machine_type_per_area'),
        ),
        migrations.AddConstraint(
            model_name='machinetyperelation',
            constraint=models.UniqueConstraint(fields=('machine_type', 'line'), name='unique_machine_type_per_line'),
        ),
    ]
