# Generated by Django 5.0.1 on 2025-04-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_rename_borrowed_permanent_borrowerrelation_permanent_borrowing'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='for_tooling',
            field=models.BooleanField(default=False),
        ),
    ]
