# Generated by Django 5.0.1 on 2025-07-07 11:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_rename_safety_number_equipmenttyperelation_m_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='equipment_type',
        ),
        migrations.RemoveField(
            model_name='component',
            name='machine_type',
        ),
        migrations.AddField(
            model_name='machinetype',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/machines/'),
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='images/machines/')),
                ('production_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.productionarea')),
            ],
        ),
        migrations.CreateModel(
            name='MachineRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('m_quantity', models.PositiveIntegerField(default=1)),
                ('factor', models.FloatField(default=1)),
                ('modify_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('added_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_ms_member', to=settings.AUTH_USER_MODEL)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.component')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.line')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.machine')),
                ('modify_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modify_ms_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='machine',
            field=models.ManyToManyField(through='main.MachineRelation', to='main.machine'),
        ),
        migrations.AddConstraint(
            model_name='machine',
            constraint=models.UniqueConstraint(fields=('name', 'production_area'), name='unique_machine_per_area'),
        ),
        migrations.AddConstraint(
            model_name='machinerelation',
            constraint=models.UniqueConstraint(fields=('machine', 'line'), name='unique_machine_per_line'),
        ),
    ]
