# Generated by Django 5.0.1 on 2024-04-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_historytrading_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='last_sn',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
