# Generated by Django 5.0.1 on 2025-04-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_location_for_tooling'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_role',
            field=models.CharField(choices=[('AME', 'AME'), ('TE', 'TE'), ('PRODUCTION', 'PRODUCTION'), ('IE', 'IE')], default='AME', max_length=255),
        ),
    ]
