# Generated by Django 5.0.1 on 2025-04-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_member_member_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_role',
            field=models.CharField(choices=[('NONE', 'NONE'), ('AME', 'AME'), ('TE', 'TE'), ('PRODUCTION', 'PRODUCTION'), ('IE', 'IE')], default='NONE', max_length=255),
        ),
    ]
