# Generated by Django 5.0.1 on 2025-07-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_component_equipment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='type',
            field=models.CharField(choices=[('DSM', 'DSM'), ('OFFLINE', 'OFFLINE')], default='DSM', max_length=255),
        ),
    ]
