# Generated by Django 5.0.1 on 2025-07-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_machinerelation_unique_machine_per_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='conflict_status',
            field=models.BooleanField(default=False),
        ),
    ]
