# Generated by Django 5.0.1 on 2024-07-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_component_self_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='self_service',
            new_name='self_pickup',
        ),
        migrations.AddField(
            model_name='request',
            name='self_pickup',
            field=models.BooleanField(default=False),
        ),
    ]
