# Generated by Django 5.0.1 on 2025-05-21 10:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_member_member_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='next_inventory_date',
        ),
        migrations.AddField(
            model_name='approvedroute',
            name='approve_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approve_route', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvedroute',
            name='prepare_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prepare_route', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='component',
            name='next_inventunory_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
