# Generated by Django 5.0.1 on 2025-05-21 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_component_next_inventory_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='next_inventunory_date',
            new_name='next_inventory_date',
        ),
    ]
