# Generated by Django 5.0.1 on 2024-10-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_request_scrap_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='unique_component',
            field=models.BooleanField(default=False),
        ),
    ]
