# Generated by Django 5.0.1 on 2025-05-21 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_rename_next_inventunory_date_component_next_inventory_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvedroute',
            name='prepare_route',
        ),
    ]
