# Generated by Django 5.0.1 on 2025-05-21 11:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_remove_approvedroute_prepare_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='historytrading',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
