# Generated by Django 5.0.1 on 2025-05-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_historytrading_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_local',
            field=models.BooleanField(default=False),
        ),
    ]
