# Generated by Django 5.0.1 on 2025-05-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='pickup_status',
            field=models.BooleanField(default=False),
        ),
    ]
