# Generated by Django 5.0.1 on 2025-05-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_request_pickup_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_administrator',
            field=models.BooleanField(default=False),
        ),
    ]
