# Generated by Django 5.0.1 on 2025-06-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_member_is_administrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, upload_to='person_picture/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_role',
            field=models.CharField(choices=[('NONE', 'NONE'), ('AE', 'AE'), ('ME', 'ME'), ('TE', 'TE'), ('PRODUCTION', 'PRODUCTION'), ('IE', 'IE'), ('AME', 'AME')], default='NONE', max_length=255),
        ),
    ]
