# Generated by Django 5.0.1 on 2025-06-11 09:33

import django.db.models.deletion
import django.utils.timezone
import main.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_member_image_alter_member_member_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftDuty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shift', models.CharField(choices=[('DAY', 'DAY'), ('NIGHT', 'NIGHT')], default='DAY', max_length=255)),
                ('period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('period_end', models.DateTimeField(default=main.models.one_week_later)),
                ('production_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.productionarea')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftDutyRelative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shift_duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shiftduty')),
            ],
        ),
        migrations.AddField(
            model_name='shiftduty',
            name='members',
            field=models.ManyToManyField(through='main.ShiftDutyRelative', to=settings.AUTH_USER_MODEL),
        ),
    ]
