# Generated by Django 5.0.1 on 2025-06-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_shiftduty_shiftdutyrelative_shiftduty_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='lineId',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='tel',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
