# Generated by Django 5.0.1 on 2025-06-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_member_lineid_member_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftduty',
            name='shift',
        ),
        migrations.AddField(
            model_name='shiftdutyrelative',
            name='shift',
            field=models.CharField(choices=[('DAY', 'DAY'), ('NIGHT', 'NIGHT')], default='DAY', max_length=255),
        ),
    ]
