# Generated by Django 5.0.1 on 2025-06-13 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_rename_lineid_member_line_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftduty',
            name='members',
        ),
        migrations.AddField(
            model_name='shiftduty',
            name='member',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shiftduty',
            name='shift',
            field=models.CharField(choices=[('DAY', 'DAY'), ('NIGHT', 'NIGHT')], default='DAY', max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_role',
            field=models.CharField(choices=[('NONE', 'NONE'), ('User', 'User'), ('Fixture Staff', 'Fixture Staff'), ('Spare Part Staff', 'Spare Part Staff'), ('Modify Part Staff', 'Modify Part Staff'), ('Management Staff', 'Management Staff'), ('-', '-')], default='NONE', max_length=255),
        ),
        migrations.DeleteModel(
            name='ShiftDutyRelative',
        ),
    ]
