# Generated by Django 5.0.1 on 2025-07-01 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_remove_shiftduty_members_shiftduty_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttyperelation',
            name='factor',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='equipmenttyperelation',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.line'),
        ),
        migrations.AddField(
            model_name='machinetyperelation',
            name='factor',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='machinetyperelation',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.line'),
        ),
    ]
