# Generated by Django 5.0.1 on 2025-07-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_alter_equipmenttype_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='equipmenttype',
            constraint=models.UniqueConstraint(fields=('name', 'production_area'), name='unique_equipment_type_per_area'),
        ),
        migrations.AddConstraint(
            model_name='machinetype',
            constraint=models.UniqueConstraint(fields=('name', 'production_area'), name='unique_machine_type_per_area'),
        ),
    ]
