# Generated by Django 5.0.1 on 2025-07-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_equipmenttype_unique_equipment_type_per_area_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='equipmenttyperelation',
            constraint=models.UniqueConstraint(fields=('equipment_type', 'line'), name='unique_equipment_type_per_line'),
        ),
        migrations.AddConstraint(
            model_name='machinetyperelation',
            constraint=models.UniqueConstraint(fields=('machine_type', 'line'), name='unique_machine_type_per_line'),
        ),
    ]
