# Generated by Django 5.0.1 on 2025-07-02 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_equipmenttyperelation_unique_equipment_type_per_line_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmenttyperelation',
            old_name='safety_number',
            new_name='m_quantity',
        ),
        migrations.RenameField(
            model_name='machinetyperelation',
            old_name='safety_number',
            new_name='m_quantity',
        ),
        migrations.RemoveField(
            model_name='equipmenttype',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='machinetype',
            name='quantity',
        ),
    ]
