# Generated by Django 5.0.1 on 2025-07-02 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_rename_safety_number_equipmenttyperelation_m_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='equipmenttyperelation',
            name='unique_equipment_type_per_line',
        ),
        migrations.RemoveConstraint(
            model_name='machinetyperelation',
            name='unique_machine_type_per_line',
        ),
    ]
